# Generated by Django 5.2.6 on 2025-09-05 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50, unique=True, verbose_name='Protocolo')),
                ('servico_realizado', models.CharField(max_length=255, verbose_name='Serviço Realizado')),
                ('data_conclusao', models.DateField(verbose_name='Data de Conclusão')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('secretaria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Secretaria Responsável')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidadao.municipe', verbose_name='Munícipe')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('respondida', models.BooleanField(default=False)),
                ('nota_geral', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Nota Geral do Atendimento')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário do Munícipe')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cidadao.atendimento', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Pesquisa de Satisfação',
                'verbose_name_plural': 'Pesquisas de Satisfação',
            },
        ),
    ]
