# Generated by Django 5.2.6 on 2025-09-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0002_atendimento_pesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Secretaria')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidadao.secretaria', verbose_name='Secretaria Responsável'),
        ),
    ]
