# Generated by Django 5.2.6 on 2025-09-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0003_secretaria_alter_atendimento_secretaria'),
    ]

    operations = [
    ]
