# Generated by Django 5.2.6 on 2025-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0004_populate_secretaria_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='secretaria_antiga',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Secretaria (Texto Antigo)'),
        ),
    ]
