# Generated by Django 5.2.6 on 2025-09-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0005_atendimento_secretaria_antiga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='secretaria_antiga',
        ),
    ]
