# Generated by Django 5.2.6 on 2025-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0006_remove_atendimento_secretaria_antiga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
    ]
