# Generated by Django 5.2.6 on 2025-10-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0007_alter_pesquisa_data_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Entidade')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='secretaria',
            options={'ordering': ['nome'], 'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='servico_realizado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serviço Realizado (Antigo)'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria/Serviço')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidadao.secretaria', verbose_name='Secretaria Responsável')),
            ],
            options={
                'verbose_name': 'Categoria (Serviço)',
                'verbose_name_plural': 'Categorias (Serviços)',
                'ordering': ['secretaria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidadao.categoria', verbose_name='Categoria do Serviço'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cidadao.entidade', verbose_name='Entidade'),
        ),
        migrations.CreateModel(
            name='UnidadeAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Unidade Administrativa')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidadao.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Unidade Administrativa',
                'verbose_name_plural': 'Unidades Administrativas',
                'ordering': ['secretaria', 'nome'],
                'unique_together': {('secretaria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='unidade_adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cidadao.unidadeadm', verbose_name='Unidade Adm. (Opcional)'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('secretaria', 'nome')},
        ),
    ]
