# Generated by Django 5.2.6 on 2025-10-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0008_entidade_alter_secretaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prazo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo (em dias)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Serviço', 'Serviço'), ('Ouvidoria', 'Ouvidoria')], default='Serviço', max_length=20, verbose_name='Tipo'),
        ),
    ]
