# Generated by Django 5.2.6 on 2025-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0009_categoria_prazo_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
    ]
