# Generated by Django 5.2.6 on 2025-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidadao', '0010_atendimento_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
